name: 'Deploy All Bicep Modules'
description: 'List all files in directory with extension'
inputs:
  directory_path:  # id of input
    description: 'The directory to search in'
    required: true
    default: './'
  extension:
    description: 'The extension to filter'
    required: true
    default: '*.*'
  containerRegistry:
    description: 'Container Registry data'
    required: true
    default: ''
  version:
    description: 'The version of modules'
    required: true
    default: ''
outputs:
  result: # id of output
    description: 'Result message'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.directory_path }}
    - ${{ inputs.extension }}
    - ${{ inputs.containerRegistry}}
    - ${{ inputs.version}}