# This is a basic workflow to help you get started with Actions

name: Bicep Modules deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure LogIn
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Deploy Modules
        id: deployment
        uses: ./
        with:
          directory_path: "./"
          extension: '*.bicep'
          containerRegistry: ${{ secrets.CONTAINER_REGISTRY }}
          version: "v6.0"
          clientId: ${{ secrets.AZURE_CLIENT_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tennantId: ${{ secrets.AZURE_TENANT_ID }}
      
      - name: Result
        run: |
          echo ${{ steps.deployment.outputs.result }}
